version: '3.4'

services:

  backend:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    command: uvicorn .main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./client
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
