version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP протокол
      - "15672:15672"  # Web интерфейс
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server/app:/app/app
      - ./services/shared:/shared
    environment:
      - SECRET_KEY=mysecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRES_MINUTES=60
      - PYTHONPATH=/app
    ports:
      - "5000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  auth:
    image: kosmixgt/mailforge-auth:latest
    depends_on:
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    volumes:
      - ./services/auth/app:/app/app
      - ./services/shared:/shared
      - ./.env:/app/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql+asyncpg://ukjytlfedcwkuoctmf1q:pf5TFMPUO9SSX0D5eoqMJfEu2BRoD2@batop7otdx5qsxwciuwv-postgresql.services.clever-cloud.com:50013/batop7otdx5qsxwciuwv
      - PYTHONPATH=/app
    ports:
      - "8001:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  mailing:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/mailing/Dockerfile
    volumes:
      - ./services/mailing/app:/app/app
      - ./services/shared:/shared
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://ukjytlfedcwkuoctmf1q:pf5TFMPUO9SSX0D5eoqMJfEu2BRoD2@batop7otdx5qsxwciuwv-postgresql.services.clever-cloud.com:50013/batop7otdx5qsxwciuwv
      - PYTHONPATH=/app
    ports:
      - "8002:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  delivery:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: services/delivery/Dockerfile
    volumes:
      - ./services/delivery/app:/app/app
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://ukjytlfedcwkuoctmf1q:pf5TFMPUO9SSX0D5eoqMJfEu2BRoD2@batop7otdx5qsxwciuwv-postgresql.services.clever-cloud.com:50013/batop7otdx5qsxwciuwv
      - PYTHONPATH=/app
    ports:
      - "8003:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
  
  history:
    build:
      context: .
      dockerfile: services/history/Dockerfile
    volumes:
      - ./services/history/app:/app/app
      - ./services/shared:/shared
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://ukjytlfedcwkuoctmf1q:pf5TFMPUO9SSX0D5eoqMJfEu2BRoD2@batop7otdx5qsxwciuwv-postgresql.services.clever-cloud.com:50013/batop7otdx5qsxwciuwv
      - PYTHONPATH=/app
    ports:
      - "8004:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000


  # frontend:
  #   build: ./client
  #   environment:
  #     - VUE_APP_BACKEND_URL=http://server:5000
  #   ports:
  #     - 8080:80
