version: '3.4'

services:

  backend:
    build: ./server
    environment:
        - SECRET_KEY=mysecretkey
        - ALGORITHM=HS256
        - ACCESS_TOKEN_EXPIRES_MINUTES=60
        - DATABASE_URL=postgresql://ukjytlfedcwkuoctmf1q:pf5TFMPUO9SSX0D5eoqMJfEu2BRoD2@batop7otdx5qsxwciuwv-postgresql.services.clever-cloud.com:50013/batop7otdx5qsxwciuwv
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./client
    environment:
      - VUE_APP_BACKEND_URL=http://backend:5000  # Используем имя сервиса "backend"
    ports:
      - 8080:80
